# Generated by Django 4.2.6 on 2024-03-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHBS', '0009_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
