# Generated by Django 4.2.6 on 2024-03-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHBS', '0010_remove_product_digital_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
