# Generated by Django 4.2.6 on 2024-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHBS', '0011_product_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hide',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
